# Generated by Django 3.2.25 on 2024-10-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAsked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('question_asked', models.CharField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='faq',
            name='email',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='name',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_asked',
        ),
    ]
