# Generated by Django 3.2.25 on 2024-10-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_rename_questionasked_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_asked',
            field=models.TextField(),
        ),
    ]
