# Generated by Django 3.2.25 on 2024-10-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviews_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='approved',
        ),
    ]
