# Generated by Django 3.2.25 on 2024-11-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_reviews_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['created_on'], 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AddField(
            model_name='reviews',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
